# Basic Python

## 1. Split this string

In [1]:
s = "Hi there Sam!"

In [2]:
s.split(" ")

['Hi', 'there', 'Sam!']

*`italicized text`*## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [5]:
planet= "Earth"
diameter = 12742

In [6]:
print("The diameter of "+planet+" is "+str(diameter)+" kilometers.")

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [7]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [8]:
print(d['k1'][3]['tricky'][3]['target'][3])

hello


# Numpy

In [9]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
result=np.ones(10)*5
print(result)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [12]:
np.arange(20,36,2)

array([20, 22, 24, 26, 28, 30, 32, 34])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [13]:
a=np.arange(0,9)
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [14]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
result = np.concatenate((array1, array2))
print(result)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [16]:
import pandas as pd


In [17]:
df = pd.DataFrame(np.random.randint(0,100,size=(3, 2)), columns=list('AB'))
print(df)

    A   B
0  20  67
1  79  49
2  14  19


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [18]:
import pandas as pd 
per1 = pd.date_range(start ='1-1-2023', end ='5-10-2023', freq ='10D')
  
for val in per1:
    print(val)

2023-01-01 00:00:00
2023-01-11 00:00:00
2023-01-21 00:00:00
2023-01-31 00:00:00
2023-02-10 00:00:00
2023-02-20 00:00:00
2023-03-02 00:00:00
2023-03-12 00:00:00
2023-03-22 00:00:00
2023-04-01 00:00:00
2023-04-11 00:00:00
2023-04-21 00:00:00
2023-05-01 00:00:00


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [19]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [20]:
import pandas
df = pandas.DataFrame(lists, columns =['SNo.', 'Name', 'Age']) 
print(df)

   SNo. Name  Age
0     1  aaa   22
1     2  bbb   25
2     3  ccc   24
